### ISSUE TITLE
using the example code

### ISSUE THREAD

**Issue by dcsan** [vdemedes/mongorito#96] opened 2016-02-18 16:58 UTC
new to ES6 generators, forgive me if this is a silly question...
when i tried the quick start code, with a complete file as below I get:

```
yield story.save();

SyntaxError: Unexpected strict mode reserved word
```

is this because that needs to be inside a generator?

[related SO question](http://stackoverflow.com/questions/28414973/unexpected-strict-mode-reserved-word-yield-node-v0-11-harmony-es6)

```
"use strict";

var Mongorito = require('mongorito');

var Model = Mongorito.Model;

var Story = Model.extend({
    collection: 'stories',
});

// Story.init = function() {
//     console.log('stories.init');
// };

let story = new Story({
    cname: 'picnic',
    code: 'some code goes here'
});

yield story.save();
```

refs
http://eslint.org/docs/rules/require-yield

**Comment by dcsan** [comment] 2016-02-18 17:43
OK if I had RTFM: 
In addition to all that, all code that contains generators and yield statements needs to be wrapped into co or similar tools, that handle generators. This may be confusing at first, but in practice, it is very simple. Read co’s Readme.md to understand how it works better.

however, I created an example using this ref:

http://stackoverflow.com/questions/28414973/unexpected-strict-mode-reserved-word-yield-node-v0-11-harmony-es6

```
    co(function*() {
      console.log('before save', story);
      yield story.save();
      console.log('after save', story);
    })
      .catch(function(err) {
        console.error(err);
    });

```

however all I see is the `before save` log.

```
  Story before save +0ms Model {
  attributes: { cname: 'picnic', code: 'some code goes here' },
  changed: {},
  previous: {},
  options: {} }
Failed to load c++ bson extension, using pure JS version
... rest of startup log
```

so it looks like something fails silently within the `yield story.save()`
any suggestions what i could do to debug that?

**Comment by edravis** [comment] 2016-02-20 19:25
+1 

For me, the outputed error is:
`[TypeError: Cannot read property 's' of undefined]`

Also, I ran into the same troubles that @dcsan so maybe it's to change the getting started because I think that [this answer](https://github.com/vdemedes/mongorito/issues/7) is not right.

**Comment by dcsan** [comment] 2016-02-20 21:18
@edravis i remember seeing that error too. this lib seems to not be functional currently.

**Comment by vdemedes** [comment] 2016-02-21 16:12
This issue is a duplicate of #93, check out my answer there ;)

**Closed by vdemedes** 2016-02-21 16:12 UTC

**Comment by vdemedes** [comment] 2016-02-21 17:27
As for example code, I added [examples](https://github.com/vdemedes/mongorito/tree/master/examples) directory and updated Readme with a lot of code snippets.
